/**
 * Morning Briefing Email Service — PIX-134 / FEAT-13
 *
 * Sends timezone-batched morning briefing emails to opted-in users.
 * Run hourly: each invocation sends to users whose local time is 06:00-08:00.
 *
 * Content sourced from DailyForecast.forecast (pre-generated by forecast-cron at 02:00 UTC).
 *
 * Tier variants:
 *   FREE     — moon phase + energy teaser + upgrade CTA (active last 7 days only)
 *   PRO      — full: moon phase, energy, top transits, tip
 *   PREMIUM  — full + one-line Oracle Insight (forecast.oracleInsight)
 */

import { render } from '@react-email/render';
import { Resend } from 'resend';
import crypto from 'crypto';
import { prisma } from '../../utils/prisma';
import { redisClient } from '../../utils/redis';
import {
  MorningBriefingEmail,
  type TransitHighlight,
} from '../../emails/MorningBriefingEmail';
import { getStoredForecast } from '../forecast-cron';

const FRONTEND_URL = process.env.FRONTEND_URL || 'https://astrologa.bg';
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'noreply@astrologa.bg';

function getResend() {
  return new Resend(process.env.RESEND_API_KEY);
}

function todayString(): string {
  return new Date().toISOString().split('T')[0];
}

function delay(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ─── URL helpers ──────────────────────────────────────────────────────────────

function buildUnsubscribeUrl(token: string, language: string): string {
  const locale = language === 'bg' ? '' : 'en/';
  return `${FRONTEND_URL}/${locale}notifications/unsubscribe?token=${token}&type=morningBriefing`;
}

function buildForecastUrl(language: string): string {
  const locale = language === 'bg' ? '' : 'en/';
  return `${FRONTEND_URL}/${locale}forecast?ref=morning-briefing&utm_source=email&utm_medium=morning_briefing`;
}

function buildUpgradeUrl(language: string): string {
  const locale = language === 'bg' ? '' : 'en/';
  return `${FRONTEND_URL}/${locale}pricing?ref=morning-briefing&utm_source=email&utm_medium=morning_briefing`;
}

// ─── Timezone-batched window check ───────────────────────────────────────────

/**
 * Returns true if the user's current local hour is in the 06:00–08:00 send window.
 * Uses the IANA timezone string from BirthProfile.
 */
function isInSendWindow(timezone: string): boolean {
  try {
    const formatter = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hour: 'numeric',
      hour12: false,
    });
    const localHour = parseInt(formatter.format(new Date()), 10);
    return localHour >= 6 && localHour < 8;
  } catch {
    // Unknown/invalid timezone — skip this user
    return false;
  }
}

// ─── Date formatting ──────────────────────────────────────────────────────────

function formatDateForEmail(language: string): string {
  const now = new Date();
  if (language === 'bg') {
    const bgMonths = [
      'януари', 'февруари', 'март', 'април', 'май', 'юни',
      'юли', 'август', 'септември', 'октомври', 'ноември', 'декември',
    ];
    const bgDays = ['неделя', 'понеделник', 'вторник', 'сряда', 'четвъртък', 'петък', 'събота'];
    return `${bgDays[now.getDay()]}, ${now.getDate()} ${bgMonths[now.getMonth()]} ${now.getFullYear()}`;
  }
  return now.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
}

function formatShortDateForSubject(language: string): string {
  const now = new Date();
  if (language === 'bg') {
    const bgMonths = ['яну', 'фев', 'мар', 'апр', 'май', 'юни', 'юли', 'авг', 'сеп', 'окт', 'ное', 'дек'];
    return `${now.getDate()} ${bgMonths[now.getMonth()]}`;
  }
  return now.toLocaleDateString('en-GB', { day: 'numeric', month: 'long' });
}

// ─── Redis dedup + failure tracking ──────────────────────────────────────────

async function checkAndMarkSent(userId: string, date: string): Promise<boolean> {
  const key = `email_morning_briefing:${userId}:${date}`;
  const existing = await redisClient.get(key);
  if (existing) return false;
  await redisClient.setEx(key, 60 * 60 * 48, '1');
  return true;
}

async function clearDedup(userId: string, date: string): Promise<void> {
  await redisClient.del(`email_morning_briefing:${userId}:${date}`);
}

async function handleSendFailure(userId: string): Promise<void> {
  const key = `email_morning_briefing_fail:${userId}`;
  const current = await redisClient.get(key);
  const count = parseInt(current || '0', 10) + 1;
  await redisClient.setEx(key, 60 * 60 * 24 * 30, String(count));

  if (count >= 3) {
    await prisma.notificationPreference.updateMany({
      where: { userId },
      data: { morningBriefing: false },
    });
    await redisClient.del(key);
    console.log(`[MorningBriefing] Auto-disabled morningBriefing for ${userId} after 3 consecutive failures`);
  }
}

async function resetFailureCounter(userId: string): Promise<void> {
  await redisClient.del(`email_morning_briefing_fail:${userId}`);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function ensureUnsubscribeToken(userId: string): Promise<string> {
  const pref = await prisma.notificationPreference.findUnique({ where: { userId } });
  if (pref?.unsubscribeToken) return pref.unsubscribeToken;

  const token = crypto.randomBytes(32).toString('hex');
  await prisma.notificationPreference.upsert({
    where: { userId },
    update: { unsubscribeToken: token },
    create: { userId, unsubscribeToken: token },
  });
  return token;
}

/** Extract top transits from forecast data for email display */
function extractTopTransits(forecastData: any, language: 'bg' | 'en'): TransitHighlight[] {
  const transits: any[] = forecastData?.transits ?? [];
  return transits
    .filter((t: any) => t.aspectToNatal)
    .slice(0, 3)
    .map((t: any) => ({
      planet: language === 'bg' ? (t.planetBg || t.planet) : t.planet,
      sign: language === 'bg' ? (t.signBg || t.sign) : t.sign,
      influence: t.aspectToNatal?.influence ?? 'neutral',
      description: language === 'bg'
        ? (t.aspectToNatal?.descriptionBg || t.aspectToNatal?.description || '')
        : (t.aspectToNatal?.description || ''),
    }));
}

// ─── Main export ──────────────────────────────────────────────────────────────

export interface MorningBriefingResult {
  processed: number;
  sent: number;
  skippedWindow: number;
  errors: number;
}

/**
 * Send morning briefing emails to users whose local time is 06:00-08:00.
 * Called hourly. Redis dedup ensures one email per user per day.
 */
export async function sendMorningBriefingEmails(): Promise<MorningBriefingResult> {
  const date = todayString();
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

  const users = await prisma.user.findMany({
    where: {
      emailVerified: true,
      isSuspended: false,
      notificationPreference: {
        morningBriefing: true,
        emailEnabled: true,
      },
      OR: [
        { tier: { in: ['PRO', 'PREMIUM'] } },
        { tier: 'FREE', lastQueryDate: { gte: sevenDaysAgo } },
      ],
      // Must have a BirthProfile (for timezone) and BirthChart (for forecast)
      birthProfiles: { some: {} },
      birthChart: { isNot: null },
    },
    select: {
      id: true,
      email: true,
      fullName: true,
      language: true,
      tier: true,
      birthProfiles: {
        take: 1,
        select: { timezone: true },
        orderBy: { createdAt: 'asc' },
      },
    },
  });

  let processed = 0;
  let sent = 0;
  let skippedWindow = 0;
  let errors = 0;

  for (const user of users) {
    processed++;

    const timezone = user.birthProfiles[0]?.timezone;
    if (!timezone) { skippedWindow++; continue; }

    // Only send to users in the 06:00-08:00 local window
    if (!isInSendWindow(timezone)) { skippedWindow++; continue; }

    try {
      const canSend = await checkAndMarkSent(user.id, date);
      if (!canSend) continue;

      const lang = (user.language || 'bg') as 'bg' | 'en';
      const tier = user.tier as 'FREE' | 'PRO' | 'PREMIUM';

      let moonPhase = 'Waxing Gibbous';
      let moonPhaseBg: string | undefined;
      let moonSign: string | undefined;
      let moonSignBg: string | undefined;
      let moonIllumination: number | undefined;
      let energy: 'high' | 'medium' | 'low' = 'medium';
      let transits: TransitHighlight[] = [];
      let tip: string | undefined;
      let tipBg: string | undefined;
      let oracleInsight: string | undefined;

      if (tier === 'PRO' || tier === 'PREMIUM') {
        const stored = await getStoredForecast(user.id, date);
        const forecastData = stored?.forecast as any;

        if (!forecastData) {
          // Forecast cron hasn't run yet — skip and allow retry
          await clearDedup(user.id, date);
          continue;
        }

        moonPhase = forecastData.moonPhase?.phase || 'Waxing Gibbous';
        moonPhaseBg = forecastData.moonPhase?.phaseBg;
        moonSign = forecastData.moonPhase?.sign;
        moonSignBg = forecastData.moonPhase?.signBg;
        moonIllumination = forecastData.moonPhase?.illumination;
        energy = forecastData.energy || 'medium';
        transits = extractTopTransits(forecastData, lang);
        tip = forecastData.recommendations?.[0];
        tipBg = forecastData.recommendationsBg?.[0];

        if (tier === 'PREMIUM') {
          oracleInsight = forecastData.oracleInsight ?? undefined;
        }
      }

      const token = await ensureUnsubscribeToken(user.id);
      const dateStr = formatDateForEmail(lang);
      const shortDate = formatShortDateForSubject(lang);

      const subject = lang === 'bg'
        ? `🌙 Твоят сутрешен брифинг за ${shortDate}`
        : `🌙 Your morning briefing for ${shortDate}`;

      const html = await render(
        MorningBriefingEmail({
          tier,
          language: lang,
          firstName: user.fullName ?? undefined,
          date: dateStr,
          moonPhase,
          moonPhaseBg,
          moonSign,
          moonSignBg,
          moonIllumination,
          energy,
          transits: tier !== 'FREE' ? transits : undefined,
          tip: tier !== 'FREE' ? tip : undefined,
          tipBg: tier !== 'FREE' ? tipBg : undefined,
          oracleInsight,
          forecastUrl: buildForecastUrl(lang),
          upgradeUrl: buildUpgradeUrl(lang),
          unsubscribeUrl: buildUnsubscribeUrl(token, lang),
        }),
      );

      const resend = getResend();
      await resend.emails.send({ from: FROM_EMAIL, to: user.email, subject, html });

      await resetFailureCounter(user.id);
      sent++;
    } catch (err) {
      errors++;
      console.error(`[MorningBriefing] Error sending to user ${user.id}:`, err);
      await handleSendFailure(user.id);
    }

    await delay(2000);
  }

  console.log(`[MorningBriefing] ${date}: processed=${processed}, sent=${sent}, skippedWindow=${skippedWindow}, errors=${errors}`);
  return { processed, sent, skippedWindow, errors };
}
